### ISSUE TITLE
`libnpmconfig` is deprecated in favor of `@npmcli/config`

### ISSUE THREAD

**Issue by JounQin** [wooorm/load-plugin#13]

**Comment by wooorm** [comment]
Open to that, but last I checked that didn’t do what we use `libnpmconfig` for 🤷‍♂️

https://github.com/wooorm/load-plugin/blob/1dfd259c0ead3c327510a5eb3de974f2011ed6b6/index.js#L39-L44

**Comment by JounQin** [comment]
Maybe we should raise an issue for alternative on upstream?

**Comment by wooorm** [comment]
Solved! I think it’s a potentially breaking change though, so went with a major
