### ISSUE TITLE
Wrong detection of npm prefix on windows

### ISSUE THREAD

**Issue by zobzn** [wooorm/load-plugin#5]
Hi. You rely on `npm-prefix` package for detecting npm prefix.
But this package is very outdated I suppose.
At least it may give wrong results on windows.

By default nodejs with npm are installing into 'system' folder:

- `C:\Program Files\nodejs\node.exe`
- `C:\Program Files\nodejs\npm.cmd`
- `C:\Program Files\nodejs\node_modules\npm\...`

In this situation the `npm-prefix` package correctly returns `C:\Program Files\nodejs`.

But... all consequent global installs go to user's folder (without requirements of privileged access to system folders):
`C:\Users\{username}\AppData\Roaming\npm\node_modules\...`
`npm i -g npm` becomes `C:\Users\{username}\AppData\Roaming\npm\node_modules\npm\...`
`npm i -g remark-cli` becomes `C:\Users\{username}\AppData\Roaming\npm\node_modules\remark-cli\...`
`npm i -g remark-html` becomes `C:\Users\{username}\AppData\Roaming\npm\node_modules\remark-html\...`

And here arises the problem with `npm-prefix`.
It still returns `C:\Program Files\nodejs` but not the actual `C:\Users\{username}\AppData\Roaming\npm`.
Eventually your `load-plugin` searches for modules in a wrong directory.

So I suggest you to find another solution.
Some other package or maybe just `npm config get prefix`?

Thank you.

**Comment by ChristianMurphy** [comment]
Replacing `npm-prefix` with `libnpm` may resolve the issue. https://github.com/npm/libnpm
Would you be interested in opening a pull request?

**Comment by zobzn** [comment]
`libnpm`'s getPrefix is just a wrapper on `find-npm-prefix` which uses promises.
Should we also switch to promises?
or add findPrefixSync method to `find-npm-prefix`?
or create something like `find-npm-prefix-sync`?
or write own findNpmPrefix here in place?

**Comment by wooorm** [comment]
I think that small PRs are generally a good thing, so change the least amount of code possible, other changes can go in different PRs.
Thanks for working on a PR, @zobzn!

**Comment by zobzn** [comment]
I'm not that good contributor in open source projects, I may not fully understand what is the least amount of code change possible :) Firstly, I'd appreciate if someone could check that I didn't break something. Secondly, point me out what exactly I can reduce in the pull request. Thank you all.

**Comment by wooorm** [comment]
Released as 3.0.0!
